name: Deployment
on: push
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Run Deploy
        run: npm run build
  # test:
  #   needs: lint
  #   runs-on: macos-latest
  #   steps:
  #     - name: Get Code
  #       uses: actions/checkout@v3
  #     - name: Install node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run test
  #       run: npm run test
  # deploy:
  #   needs: test
  #   runs-on: macos-latest
  #   steps:
  #     - name: Get Code
  #       uses: actions/checkout@v3
  #     - name: Install node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run Deploy
  #       run: npm run build